// endpoint de cadastro
POST https://lama-bianca-paccola.onrender.com/user/signup
Content-Type: application/json

{
    "email": "teste@email.com",
    "name": "User Teste",
    "password": "123abc",
    "role": "admin"
}

###

// endpoint de login
POST https://lama-bianca-paccola.onrender.com/user/login
Content-Type: application/json

{
    "email": "teste@email.com",
    "password": "123abc"
}

### 

// Endpoint para registrar uma banda
POST https://lama-bianca-paccola.onrender.com/bands/register
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOWYzMzI3LWI3ODUtNGNjZi04ZGY4LTgxY2M4MTZiZjJmMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTI2NzYzNCwiZXhwIjoxNjc5NDQwNDM0fQ.8I0VMwQdALJhcENO1lQYoCyCuAaJDdz1i579pUvw9GU

{
    "name": "Crazy Lollipop",
    "musicGenre": "Punk",
    "responsible": "John Hurts"
}

###

// Endpoint para buscar uma banda pelo nome - pode-se passar tanto o nome completo separando as setenças com '+' ou por uma parte que contenha no nome, no segundo caso vem todas que encontrar
GET https://lama-bianca-paccola.onrender.com/bands/details?name=The+Brothers+Band
Content-Type: application/json

###

//Endpoint para buscar uma banda pelo id
GET https://lama-bianca-paccola.onrender.com/bands/details?id=4b123454-8479-4790-b60c-5efc77106258
Content-Type: application/json

###

//Endpoint para criar um show
POST https://lama-bianca-paccola.onrender.com/shows/post
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOWYzMzI3LWI3ODUtNGNjZi04ZGY4LTgxY2M4MTZiZjJmMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTI2NzYzNCwiZXhwIjoxNjc5NDQwNDM0fQ.8I0VMwQdALJhcENO1lQYoCyCuAaJDdz1i579pUvw9GU

{
    "weekDay": "sábado",
    "startTime": 18,
    "endTime": 20,
    "bandId": "4b123454-8479-4790-b60c-5efc77106258"
}

###

// Endpoint para buscar os shows pelo dia
GET https://lama-bianca-paccola.onrender.com/shows/sábado
Content-Type: application/json