// endpoint de cadastro
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "silvia@email.com",
    "name": "Silvia Paccola",
    "password": "abc123",
    "role": "admin"
}

###

// endpoint de login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "bianca@email.com",
    "password": "123abc"
}

### 

// Endpoint para registrar uma banda
POST http://localhost:3003/bands/register
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmY2Y5NzY3LWVhMjYtNDkyYy1hMmQxLWZkNjI0M2RlNjZkZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTA5MzA3NSwiZXhwIjoxNjc5MDk2Njc1fQ.M4cQktv9HYLAeZReWN9JIonRjxhc2xIBSDQdN1X69Zk

{
    "name": "The New Band",
    "musicGenre": "Rockabilly",
    "responsible": "Rick Richards"
}