// endpoint de cadastro
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "ederson@email.com",
    "name": "Ederson Carlos",
    "password": "abc123",
    "role": "normal"
}

###

// endpoint de login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "bianca@email.com",
    "password": "123abc"
}

### 

// Endpoint para registrar uma banda
POST http://localhost:3003/bands/register
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmY2Y5NzY3LWVhMjYtNDkyYy1hMmQxLWZkNjI0M2RlNjZkZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTI1MDk4MiwiZXhwIjoxNjc5MjU0NTgyfQ.IrW9YOv3EzLa9XIOxgAVNDV5wy0HfgVQjTqq8e77cd8

{
    "name": "Sons of Anarch",
    "musicGenre": "Punk",
    "responsible": "Bruce Joe"
}

###

// Endpoint para buscar uma banda pelo nome - pode-se passar tanto o nome completo separando as setenças com '+' ou por uma parte que contenha no nome, no segundo caso vem todas que encontrar
GET http://localhost:3003/bands/details?name=The+Brothers+Band
Content-Type: application/json

###

//Endpoint para buscar uma banda pelo id
GET http://localhost:3003/bands/details?id=4b123454-8479-4790-b60c-5efc77106258
Content-Type: application/json

###

//Endpoint para criar um show
POST http://localhost:3003/shows/post
Content-Type: application/json

{
    "weekDay": "sexta",
    "startTime": 18,
    "endTime": 19,
    "bandId": "f21cc70c-0955-499b-b543-04356c3440be"
}